#!/bin/bash

case $2 in
  "/dev/input/event3")
  echo "P: /devices/platform/i8042/serio0/input/input3/event3
N: input/event3
L: 0
S: input/by-path/platform-i8042-serio-0-event-kbd
E: DEVPATH=/devices/platform/i8042/serio0/input/input3/event3
E: DEVNAME=/dev/input/event3
E: MAJOR=13
E: MINOR=67
E: SUBSYSTEM=input
E: USEC_INITIALIZED=7708374
E: KEYBOARD_KEY_81=playpause
E: KEYBOARD_KEY_82=stopcd
E: KEYBOARD_KEY_83=previoussong
E: KEYBOARD_KEY_84=nextsong
E: KEYBOARD_KEY_85=brightnessdown
E: KEYBOARD_KEY_86=brightnessup
E: KEYBOARD_KEY_87=battery
E: KEYBOARD_KEY_88=!
E: KEYBOARD_KEY_89=ejectclosecd
E: KEYBOARD_KEY_8a=suspend
E: KEYBOARD_KEY_8b=switchvideomode
E: KEYBOARD_KEY_8c=unknown
E: KEYBOARD_KEY_8f=switchvideomode
E: KEYBOARD_KEY_90=previoussong
E: KEYBOARD_KEY_91=prog1
E: KEYBOARD_KEY_92=media
E: KEYBOARD_KEY_93=unknown
E: KEYBOARD_KEY_95=camera
E: KEYBOARD_KEY_97=email
E: KEYBOARD_KEY_98=f21
E: KEYBOARD_KEY_99=nextsong
E: KEYBOARD_KEY_9a=setup
E: KEYBOARD_KEY_9b=switchvideomode
E: KEYBOARD_KEY_9e=!f21
E: KEYBOARD_KEY_a2=playpause
E: KEYBOARD_KEY_a4=stopcd
E: KEYBOARD_KEY_d8=screenlock
E: KEYBOARD_KEY_d9=f21
E: KEYBOARD_KEY_ed=media
E: ID_INPUT=1
E: ID_INPUT_KEY=1
E: ID_INPUT_KEYBOARD=1
E: ID_BUS=i8042
E: ID_SERIAL=noserial
E: ID_PATH=platform-i8042-serio-0
E: ID_PATH_TAG=platform-i8042-serio-0
E: XKBLAYOUT=fr,fr
E: XKBVARIANT=latin9,bepo
E: BACKSPACE=guess
E: XKBMODEL=pc105
E: XKBOPTIONS=grp_led:scroll
E: LIBINPUT_DEVICE_GROUP=11/1/1:isa0060/serio0
E: DEVLINKS=/dev/input/by-path/platform-i8042-serio-0-event-kbd
E: TAGS=:power-switch:
E: CURRENT_TAGS=:power-switch:
"
    exit 0;
  ;;
  "/dev/input/event20")
    echo "P: /devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2:1.0/0003:FEED:6060.008F/input/input205/event20
N: input/event20
L: 0
S: input/by-path/pci-0000:00:14.0-usb-0:2:1.0-event-kbd
S: input/by-id/usb-OLKB_Planck_0-event-kbd
E: DEVPATH=/devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2:1.0/0003:FEED:6060.008F/input/input205/event20
E: DEVNAME=/dev/input/event20
E: MAJOR=13
E: MINOR=84
E: SUBSYSTEM=input
E: USEC_INITIALIZED=53816054695
E: ID_INPUT=1
E: ID_INPUT_KEY=1
E: ID_INPUT_KEYBOARD=1
E: ID_VENDOR=OLKB
E: ID_VENDOR_ENC=OLKB
E: ID_VENDOR_ID=feed
E: ID_MODEL=Planck
E: ID_MODEL_ENC=Planck
E: ID_MODEL_ID=6060
E: ID_REVISION=0004
E: ID_SERIAL=OLKB_Planck_0
E: ID_SERIAL_SHORT=0
E: ID_TYPE=hid
E: ID_BUS=usb
E: ID_USB_INTERFACES=:030101:030000:
E: ID_USB_INTERFACE_NUM=00
E: ID_USB_DRIVER=usbhid
E: ID_PATH=pci-0000:00:14.0-usb-0:2:1.0
E: ID_PATH_TAG=pci-0000_00_14_0-usb-0_2_1_0
E: XKBLAYOUT=fr,fr
E: XKBVARIANT=latin9,bepo
E: BACKSPACE=guess
E: XKBMODEL=pc105
E: XKBOPTIONS=grp_led:scroll
E: LIBINPUT_DEVICE_GROUP=3/feed/6060:usb-0000:00:14.0-2
E: DEVLINKS=/dev/input/by-path/pci-0000:00:14.0-usb-0:2:1.0-event-kbd /dev/input/by-id/usb-OLKB_Planck_0-event-kbd
E: TAGS=:power-switch:
E: CURRENT_TAGS=:power-switch:"
    exit 0;
  ;;
  *)
    echo Error;
    exit 1;
esac;